const list = [
  { name: "Agent Carter", seasons: 2, genre: "sad", status: "Cancelled" },
  { name: "All of Us Are Dead", seasons: 1, genre: "hzv", status: "Not Done" },
  { name: "Anne Rice's Mayfair Witches", seasons: 1, genre: "tds", status: "Ended" },
  { name: "Archive81", seasons: 1, genre: "mdh", status: "Cancelled" },
  { name: "Band of Brothers", seasons: 1, genre: "wda", status: "Ended" },
  { name: "Black Knight", seasons: 1, genre: "sav", status: "Ended" },
  { name: "Black Summer", seasons: 2, genre: "dha", status: "Cancelled" },
  { name: "Chicken Nugget", seasons: 1, genre: "cmv", status: "Ended" },
  { name: "City on Fire", seasons: 1, genre: "cdv", status: "Ended" },
  { name: "Daredevil", seasons: 3, genre: "aeb", status: "Not Done" },
  { name: "Dark", seasons: 3, genre: "tmd", status: "Ended" },
  { name: "Dead Boy Detectives", seasons: 1, genre: "cdh", status: "Not Done" },
  { name: "Don't Trust the B---- In Apartment 23", seasons: 2, genre: "ovv", status: "Ended" },
  { name: "Echo", seasons: 1, genre: "abq", status: "Ended" },
  { name: "From", seasons: 2, genre: "hsv", status: "Not Done" },
  { name: "Ginny & Georgia", seasons: 2, genre: "cdv", status: "Not Done" },
  { name: "Gotham Knights", seasons: 1, genre: "acd", status: "Cancelled" },
  { name: "Grand Army", seasons: 1, genre: "kdv", status: "Ended" },
  { name: "Halo", seasons: 2, genre: "sae", status: "Cancelled" },
  { name: "Hawkeye", seasons: 1, genre: "cab", status: "Not Done" },
  { name: "House", seasons: 1, genre: "gpv", status: "Done" },
  { name: "House of The Dragons", seasons: 2, genre: "fda", status: "Not Done" },
  { name: "I Am Groot", seasons: 1, genre: "scv", status: "Not Done" },
  { name: "ICarly", seasons: 3, genre: "ocv", status: "Ended" },
  { name: "Imposters", seasons: 2, genre: "pvv", status: "Cancelled" },
  { name: "Iron Fist", seasons: 2, genre: "adq", status: "Cancelled" },
  { name: "Jessica Jones", seasons: 3, genre: "dtb", status: "Ended" },
  { name: "John Doe", seasons: 1, genre: "dsv", status: "Ended" },
  { name: "La Casa De Papel", seasons: 5, genre: "iab", status: "Ended" },
  { name: "Locke & Key", seasons: 3, genre: "hdm", status: "Ended" },
  { name: "Lockwood & Co", seasons: 1, genre: "aeh", status: "Cancelled" },
  { name: "Loki", seasons: 2, genre: "etf", status: "Not Done" },
  { name: "Love & Death", seasons: 1, genre: "dbv", status: "Ended" },
  { name: "Luke Cage", seasons: 2, genre: "abq", status: "Cancelled" },
  { name: "MacGyver", seasons: 5, genre: "eav", status: "Ended" },
  { name: "Man vs Bee", seasons: 1, genre: "cvv", status: "Ended" },
  { name: "Manhunt", seasons: 1, genre: "tdv", status: "Ended" },
  { name: "Monsters at Work", seasons: 2, genre: "cfv", status: "Ended" },
  { name: "Moon Knight", seasons: 1, genre: "aef", status: "Ended" },
  { name: "Mr. Iglesias", seasons: 3, genre: "ocv", status: "Ended" },
  { name: "Ms. Marvel", seasons: 1, genre: "eca", status: "Ended" },
  { name: "Night Has Come", seasons: 1, genre: "tmh", status: "Ended" },
  { name: "Not Dead Yet", seasons: 2, genre: "ovv", status: "Ended" },
  { name: "Orphan Black: Echoes", seasons: 1, genre: "sct", status: "Not Done" },
  { name: "Prison Break", seasons: 5, genre: "amt", status: "Ended" },
  { name: "Pyramid Game", seasons: 1, genre: "tum", status: "Ended" },
  { name: "Reacher", seasons: 2, genre: "atc", status: "Not Done" },
  { name: "Resident Evil", seasons: 1, genre: "ahd", status: "Cancelled" },
  { name: "Scream Queens", seasons: 2, genre: "hcd", status: "Ended" },
  { name: "Secret Invasion", seasons: 1, genre: "aes", status: "Ended" },
  { name: "See", seasons: 3, genre: "aes", status: "Ended" },
  { name: "Shōgun", seasons: 1, genre: "dav", status: "Ended" },
  { name: "She-Hulk Attorney at Law", seasons: 1, genre: "ecd", status: "Ended" },
  { name: "Squid Game", seasons: 1, genre: "atu", status: "Not Done" },
  { name: "Stay Close", seasons: 1, genre: "mbt", status: "Ended" },
  { name: "Ted", seasons: 1, genre: "cvv", status: "Not Done" },
  { name: "The 8 Show", seasons: 1, genre: "ctd", status: "Ended" },
  { name: "The Boss Baby Back in Business", seasons: 3, genre: "cef", status: "Ended" },
  { name: "The Defenders", seasons: 1, genre: "adq", status: "Ended" },
  { name: "The Falcon And The Winter Soldier", seasons: 1, genre: "cea", status: "Ended" },
  { name: "The Flight Attendant", seasons: 2, genre: "mct", status: "Ended" },
  { name: "The Last Of Us", seasons: 1, genre: "aew", status: "Not Done" },
  { name: "The Lazarus Project", seasons: 1, genre: "sat", status: "Cancelled" },
  { name: "The Night Agent", seasons: 1, genre: "atd", status: "Ended" },
  { name: "The Office", seasons: 9, genre: "cov", status: "Ended" },
  { name: "The Outsider", seasons: 1, genre: "hbm", status: "Cancelled" },
  { name: "The Peripheral", seasons: 1, genre: "std", status: "Cancelled" },
  { name: "The Punisher", seasons: 2, genre: "bat", status: "Ended" },
  { name: "The Queen's Gambit", seasons: 1, genre: "dvv", status: "Ended" },
  { name: "The Rookie", seasons: 6, genre: "adb", status: "Not Done" },
  { name: "The Terminal List", seasons: 1, genre: "adb", status: "Ended" },
  { name: "The Wilds", seasons: 2, genre: "dmu", status: "Cancelled" },
  { name: "The Witcher", seasons: 3, genre: "efd", status: "Not Done" },
  { name: "The Witcher Blood Origin", seasons: 1, genre: "fda", status: "Ended" },
  { name: "The Woman In The House Across The Street From The Girl In The Window", seasons: 1, genre: "mtc", status: "Ended" },
  { name: "United States of Al", seasons: 2, genre: "ocv", status: "Cancelled" },
  { name: "Wanda Vision", seasons: 1, genre: "rmd", status: "Ended" },
  { name: "Wednesday", seasons: 1, genre: "fcm", status: "Not Done" },
  { name: "What If...?", seasons: 2, genre: "aes", status: "Not Done" },
  { name: "Y The Last Man", seasons: 1, genre: "dea", status: "Ended" },
  { name: "Yellowjackets", seasons: 2, genre: "mtu", status: "Not Done" },
  { name: "Young Sheldon", seasons: 7, genre: "ocd", status: "Ended" },
];


const sortedList = list.sort((a, b) => a.name.localeCompare(b.name));

const genre = {
  a: "Action",
  b: "Crime",
  c: "Comedy",
  d: "Drama",
  e: "Adventure",
  f: "Fantasy",
  g: "Medical",
  t: "Thriller",
  h: "Horror",
  m: "Mystery",
  s: "Sci-Fi",
  r: "Romance",
  w: "War",
  i: "Heist",
  o: "Sitcom",
  k: "Adolescence",
  u: "Survival",
  p: "Dark Comedy",
  q: "Superhero",
  z: "Zombie apocalypse",
  v: "",
};
