const list = [
  { name: "Agent Carter", seasons: 2, genre: "sad" },
  { name: "Anne Rice's Mayfair Witches", seasons: 1, genre: "tds" },
  { name: "Archive81", seasons: 1, genre: "mdh" },
  { name: "Band of Brothers", seasons: 1, genre: "wda" },
  { name: "Black Knight", seasons: 1, genre: "sav" },
  { name: "Black Summer", seasons: 2, genre: "dha" },
  { name: "Chicken Nugget", seasons: 1, genre: "cmv" },
  { name: "City on Fire", seasons: 1, genre: "cdv" },
  { name: "Daredevil", seasons: 3, genre: "aeb" },
  { name: "Dark", seasons: 3, genre: "tmd" },
  { name: "Dead Boy Detectives", seasons: 1, genre: "cdh" },
  { name: "Don't Trust the B---- In Apartment 23", seasons: 2, genre: "ovv" },
  { name: "Echo", seasons: 1, genre: "abq" },
  { name: "From", seasons: 2, genre: "hsv" },
  { name: "Ginny & Georgia", seasons: 2, genre: "cdv" },
  { name: "Gotham Knights", seasons: 1, genre: "acd" },
  { name: "Grand Army", seasons: 1, genre: "kdv" },
  { name: "Halo", seasons: 2, genre: "sae" },
  { name: "Hawkeye", seasons: 1, genre: "cab" },
  { name: "House of The Dragons", seasons: 2, genre: "fda" },
  { name: "I Am Groot", seasons: 1, genre: "scv" },
  { name: "ICarly", seasons: 3, genre: "ocv" },
  { name: "Imposters", seasons: 2, genre: "pvv" },
  { name: "Iron Fist", seasons: 2, genre: "adq" },
  { name: "Jessica Jones", seasons: 3, genre: "dtb" },
  { name: "La Casa De Papel", seasons: 5, genre: "iab" },
  { name: "Locke & Key", seasons: 3, genre: "hdm" },
  { name: "Lockwood & Co", seasons: 1, genre: "aeh" },
  { name: "Loki", seasons: 2, genre: "etf" },
  { name: "Love & Death", seasons: 1, genre: "dbv" },
  { name: "Luke Cage", seasons: 2, genre: "abq" },
  { name: "MacGyver", seasons: 5, genre: "eav" },
  { name: "Man vs Bee", seasons: 1, genre: "cvv" },
  { name: "Manhunt", seasons: 1, genre: "tdv" },
  { name: "Monsters at Work", seasons: 2, genre: "cfv" },
  { name: "Moon Knight", seasons: 1, genre: "aef" },
  { name: "Mr. Iglesias", seasons: 3, genre: "ocv" },
  { name: "Ms. Marvel", seasons: 1, genre: "eca" },
  { name: "Night Has Come", seasons: 1, genre: "tmh" },
  { name: "Not Dead Yet", seasons: 2, genre: "ovv" },
  { name: "Pyramid Game", seasons: 1, genre: "tum" },
  { name: "Prison Break", seasons: 5, genre: "amt" },
  { name: "Reacher", seasons: 2, genre: "atc" },
  { name: "Resident Evil", seasons: 1, genre: "ahd" },
  { name: "Scream Queens", seasons: 2, genre: "hcd" },
  { name: "Secret Invasion", seasons: 1, genre: "aes" },
  { name: "See", seasons: 3, genre: "aes" },
  { name: "Shōgun", seasons: 1, genre: "dav" },
  { name: "She-Hulk Attorney at Law", seasons: 1, genre: "ecd" },
  { name: "Squid Game", seasons: 1, genre: "atu" },
  { name: "Stay Close", seasons: 1, genre: "mbt" },
  { name: "Ted", seasons: 1, genre: "cvv" },
  { name: "The 8 Show", seasons: 1, genre: "ctd" },
  { name: "The Boss Baby Back in Business", seasons: 3, genre: "cef" },
  { name: "The Defenders", seasons: 1, genre: "adq" },
  { name: "The Falcon And The Winter Soldier", seasons: 1, genre: "cea" },
  { name: "The Flight Attendant", seasons: 2, genre: "mct" },
  { name: "The Last Of Us", seasons: 1, genre: "aew" },
  { name: "The Lazarus Project", seasons: 1, genre: "sat" },
  { name: "The Night Agent", seasons: 1, genre: "atd" },
  { name: "The Office", seasons: 9, genre: "cov" },
  { name: "The Outsider", seasons: 1, genre: "hbm" },
  { name: "The Peripheral", seasons: 1, genre: "std" },
  { name: "The Punisher", seasons: 2, genre: "bat" },
  { name: "The Queen's Gambit", seasons: 1, genre: "dvv" },
  { name: "The Rookie", seasons: 6, genre: "adb" },
  { name: "The Terminal List", seasons: 1, genre: "adb" },
  { name: "The Wilds", seasons: 2, genre: "dmu" },
  { name: "The Witcher", seasons: 3, genre: "efd" },
  { name: "The Witcher Blood Origin", seasons: 1, genre: "fda" },
  { name: "The Woman In The House Across The Street From The Girl In The Window", seasons: 1, genre: "mtc" },
  { name: "United States of Al", seasons: 2, genre: "ocv" },
  { name: "Wanda Vision", seasons: 1, genre: "rmd" },
  { name: "Wednesday", seasons: 1, genre: "fcm" },
  { name: "What If...?", seasons: 2, genre: "aes" },
  { name: "Y The Last Man", seasons: 1, genre: "dea" },
  { name: "Yellowjackets", seasons: 2, genre: "mtu" },
  { name: "Young Sheldon", seasons: 7, genre: "ocd" }
];


const sortedList = list.sort((a, b) => a.name.localeCompare(b.name));

const genre = {
  "a": "Action",
  "b": "Crime",
  "c": "Comedy",
  "d": "Drama",
  "e": "Adventure",
  "f": "Fantasy",
  "t": "Thriller",
  "h": "Horror",
  "m": "Mystery",
  "s": "Sci-Fi",
  "r": "Romance",
  "w": "War",
  "i": "Heist",
  "o": "Sitcom",
  "k": "Adolescence",
  "u": "Survival",
  "p": "Dark Comedy",
  "q": "Superhero",
  "v": "",
};
