const seriesData = {
  "A Good Girl's Guide to Murder": {
    name: "A Good Girl's Guide to Murder",
    description:
      "Pip Fitz-Amobi, a brilliant woman, is unsure whether schoolgirl Andie Bell was killed by her lover Sal Singh five years ago; they must see how far they will go to protect Pip from learning the truth if Sal Singh turns out not to be the murderer.",
    year: "2024-",
    rating: "",
    runningTime: " 40-48 minutes",
    seasons: 1,
    episodes: 6,
    creators: "Poppy Cogan",
    director: "Dolly Wells and Tom Vaughan",
    writer: "Poppy Cogan, Ruby Thomas, Zia Ahmed and Ajoke Ibironke",
    genres: ["Mystert", "Thriller"],
    seasonsWatched: 1,
    genreChars: "mtv",
    status: "On Going",
  },
  "Agatha All Along": {
    name: "Agatha All Along",
    description:
      "Set after the events of 'WandaVision', Agatha Harkness recruits some unlikely allies on her quest to regain her former powers and uncover the secrets of the Darkhold.",
    year: "2024",
    rating: "3.8",
    runningTime: " 29-49 minutes",
    seasons: 1,
    episodes: 9,
    creators: "Jac Schaeffer",
    director: "Jac Schaeffer, Rachel Goldberg and Gandja Monteiro",
    writer:
      "Jac Schaeffer, Laura Donney, Cameron Squires, Giovanna Sarquis and others",
    genres: ["Black comedy", "Fantasy", "Superhero"],
    seasonsWatched: 1,
    genreChars: "pfq",
    status: "On Going",
  },
  "Agent Carter": {
    name: "Agent Carter",
    description:
      "Life changes for Peggy Carter after her boyfriend Steve Rogers is feared dead. Now she leads a dual life by doing administrative work as well as working as a S.H.I.E.L.D. agent under Howard Stark.",
    year: "2015-2016",
    rating: "3.7",
    runningTime: "41-43 minutes",
    seasons: 2,
    episodes: 18,
    creators: "Christopher Markus and Stephen McFeely",
    director:
      "Jennifer Getzinger, Metin Hüseyin, David Platt, Lawrence Trilling and others",
    writer:
      "Jack Kirby, Stan Lee, Christopher Markus, Stephen McFeely and others",
    genres: ["Action-adventure", "Period drama", "Spy-fi", "Superhero"],
    seasonsWatched: 2,
    genreChars: "sad",
    status: "Cancelled",
  },
  "All of Us Are Dead": {
    name: "All of Us Are Dead",
    description:
      "Trapped students must escape their high school which has become ground zero for a zombie virus outbreak.",
    year: "2022-",
    rating: "3.7",
    runningTime: "53-72 minutes",
    seasons: 1,
    episodes: 12,
    creators: "Chun Sung-il, Lee Jae-kyoo and Kim Nam-su",
    director: "Lee Jae-kyoo and Kim Nam-su",
    writer: "Chun Sung-il",
    genres: ["Coming-of-age", "Horror", "Zombie apocalypse"],
    seasonsWatched: 1,
    genreChars: "hzv",
    status: "On Going",
  },
  "Anne Rice's Mayfair Witches": {
    name: "Anne Rice's Mayfair Witches",
    description:
      "Rowan Fielding, an intuitive young neurosurgeon, discovers that she is the unlikely heir to a family of witches; as she grapples with her newfound powers, she must contend with a sinister presence that has haunted her family for generations.",
    year: "2023",
    rating: "3.6",
    runningTime: "40-60 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Michelle Ashford and Esta Spalding",
    director:
      "Michael Uppendahl, Axelle Carolyn, Haifaa Al-Mansour, Alexis Ostrander and others",
    writer:
      "Michelle Ashford, Esta Spalding, Michael Goldbach, Lindsey Villarreal and others",
    genres: ["Supernatural", "Thriller", "Drama"],
    seasonsWatched: 1,
    genreChars: "tds",
    status: "Ended",
  },
  "Archive 81": {
    name: "Archive 81",
    description:
      "An archivist takes a job restoring damaged videotapes, but finds themselves getting pulled into a mystery involving the missing director and a mysterious cult that they were documenting.",
    year: "2022",
    rating: "3.8",
    runningTime: "45-58 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Rebecca Sonnenshine",
    director:
      "Rebecca Thomas, Justin Benson, Aaron Moorhead, Haifaa Al Mansour and others",
    writer:
      "Paul Harris Boardman, Rebecca Sonnenshine, Michael Narducci, Evan Bleiweiss and others",
    genres: ["Analog horror", "Supernatural fiction", "Mystery", "Drama"],
    seasonsWatched: 1,
    genreChars: "mdh",
    status: "Cancelled",
  },
  "Band of Brothers": {
    name: "Band of Brothers",
    description:
      "The story of Easy Company, 506th Regiment of the 101st Airborne Division from 1942 to the end of World War II. A collection of fifty portraits illustrated by archive footage and recounted in voice.",
    year: "2001",
    rating: "3.1",
    runningTime: "49-70 minutes",
    seasons: 1,
    episodes: 10,
    creators: "Tom Hanks and Steven Spielberg",
    director:
      "Phil Alden Robinson, Richard Loncraine, Mikael Salomon, David Nutter and others",
    writer: "Erik Jendresen, Tom Hanks, John Orloff, E. Max Frye and others",
    genres: ["War drama"],
    seasonsWatched: 1,
    genreChars: "wda",
    status: "Ended",
  },
  "Black Knight": {
    name: "Black Knight",
    description:
      "In a dystopian future devastated by air pollution, the survival of humanity depends on a group of deliverymen known as the Black Knights who navigate the wastelands using unconventional means.",
    year: "2023",
    rating: "3.8",
    runningTime: "47-52 minutes",
    seasons: 1,
    episodes: 6,
    creators: "Cho Ui-seok and Kim Hyun-deok",
    director: "Cho Ui-seok and Kim Hyun-deok",
    writer: "Cho Ui-seok and Kim Hyun-deok",
    genres: ["Science fiction", "Dystopian", "Action"],
    seasonsWatched: 1,
    genreChars: "sav",
    status: "Ended",
  },
  "Black Summer": {
    name: "Black Summer",
    description:
      "Set in the 'Z Nation' universe, this series follows a crack team of special forces as it fights for hope in the darkest hours of the zombie apocalypse.",
    year: "2019-2021",
    rating: "3.9",
    runningTime: "21-58 minutes",
    seasons: 2,
    episodes: 16,
    creators: "Karl Schaefer and John Hyams",
    director: "John Hyams, Abram Cox",
    writer: "Karl Schaefer, John Hyams, Abram Cox, Daniel Schaefer and others",
    genres: ["Apocalyptic fiction", "Drama", "Horror", "Action"],
    seasonsWatched: 2,
    genreChars: "dha",
    status: "Cancelled",
  },
  "Chicken Nugget": {
    name: "Chicken Nugget",
    description:
      "A woman steps into an odd machine and becomes a chicken nugget; now, it's up to her father and admirer to embark on a zany quest to bring her back.",
    year: "2024-",
    rating: "3.1",
    runningTime: "28-37 minutes",
    seasons: 1,
    episodes: 10,
    creators: "Lee Byeong-heon",
    director: "Lee Byeong-heon",
    writer: "Lee Byeong-heon",
    genres: ["Comedy", "Mystery"],
    seasonsWatched: 1,
    genreChars: "cmv",
    status: "Ended",
  },
  "City on Fire": {
    name: "City on Fire",
    description:
      "A college student is found shot in Central Park on the Fourth of July, and the investigation into her shooting connects a series of citywide fires, the downtown music scene, and a wealthy uptown family.",
    year: "2023",
    rating: "3.7",
    runningTime: "46-57 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Josh Schwartz and Stephanie Savage",
    director: "Jesse Peretz, Haifaa al-Mansour, and Liz Garbus",
    writer: "Josh Schwartz and Stephanie Savage",
    genres: ["Crime", "Drama"],
    seasonsWatched: 1,
    genreChars: "cdv",
    status: "Ended",
  },
  Daredevil: {
    name: "Daredevil",
    description:
      "Matt Murdock manages to overcome the challenges that he faces due to him being blind since childhood and fights criminals as a lawyer and Daredevil.",
    year: "2015-2018",
    rating: "4.3",
    runningTime: "46-61 minutes",
    seasons: 3,
    episodes: 39,
    creators: "Drew Goddard",
    director:
      "Phil Abraham, Adam Kane, Ken Girotti, Farren Blackburn and others",
    writer: "Drew Goddard, Marco Ramirez, Joe Pokaski, Luke Kalteux and others",
    genres: ["Action-adventure", "Crime drama", "Legal drama", "Superhero"],
    seasonsWatched: 3,
    genreChars: "aeb",
    status: "On Going",
  },
  Dark: {
    name: "Dark",
    description:
      "When two children go missing in a small German town, its sinful past is exposed along with the double lives and fractured relationships that exist among four families as they search for the kids. The mystery-drama series introduces an intricate puzzle filled with twists that includes a web of curious characters, all of whom have a connection to the town's troubled history -- whether they know it or not. The story includes supernatural elements that tie back to the same town in 1986.",
    year: "2017-2020",
    rating: "4.6",
    runningTime: "44–73 minutes",
    seasons: 3,
    episodes: 26,
    creators: "Baran bo Odar and Jantje Friese",
    director: "Baran bo Odar",
    writer:
      "Baran bo Odar, Jantje Friese, Ronny Schalk, Marc O. Seng, Martin Behnke, Daphne Ferraro",
    genres: ["Science fiction", "Thriller", "Mystery", "Tragedy"],
    seasonsWatched: 3,
    genreChars: "tmd",
    status: "Ended",
  },
  "Dead Boy Detectives": {
    name: "Dead Boy Detectives",
    description:
      "Two teenage ghosts work alongside a clairvoyant to solve mysteries for their supernatural clientele, until a powerful witch complicates their plans.",
    year: "2024-",
    rating: "4.0",
    runningTime: "52-56 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Steve Yockey",
    director:
      "Lee Toland Krieger, Glen Winter, Cheryl Dunye, Andi Armaganian and others",
    writer:
      "Steve Yockey, Shoshana Sachi, Cheech Manohar, Ian Weinreich and others",
    genres: ["Comedy-drama", "Occult detective", "Supernatural horror"],
    seasonsWatched: 1,
    genreChars: "cdh",
    status: "On Going",
  },
  "Don't Trust the B---- In Apartment 23": {
    name: "Don't Trust the B---- In Apartment 23",
    description:
      "June Colburn moves to New York City from Indiana to pursue her dream job. Unfortunately, things don't work out for her and she ends up sharing an apartment with Chloe, a con artist.",
    year: "2012-2013",
    rating: "3.8",
    runningTime: "22 minutes",
    seasons: 2,
    episodes: 26,
    creators: "Nahnatchka Khan",
    director:
      "Jason Winer, Michael Spiller, Chris Koch, Nanette Burstein and others",
    writer:
      "Nahnatchka Khan, Sally Bradford McKenna, Casey Johnson, David Windsor and others",
    genres: ["Sitcom"],
    seasonsWatched: 2,
    genreChars: "oov",
    status: "Ended",
  },
  Echo: {
    name: "Echo",
    description:
      "Maya Lopez's ruthless behavior in New York City catches up with her in her hometown; she must face her past, reconnect with her Native American roots and embrace the meaning of family and community.",
    year: "2023-2024",
    rating: "3.7",
    runningTime: "37-51 minutes",
    seasons: 1,
    episodes: 5,
    creators: "Marion Dayre",
    director: "Sydney Freeland and Catriona McKenzie",
    writer:
      "Marion Dayre, Josh Feldman, Steven Paul Judd, Ken Kristensen and others",
    genres: ["Action-adventure", "Crime", "Superhero"],
    seasonsWatched: 1,
    genreChars: "abq",
    status: "Ended",
  },
  From: {
    name: "From",
    description:
      "The residents of a small town struggle to find a way out when mysterious unknown forces keep them from leaving.",
    year: "2022-",
    rating: "4.6",
    runningTime: "45–59 minutes",
    seasons: 3,
    episodes: 26,
    creators: "John Griffin",
    director: "Jack Bender, Brad Turner, Jennifer Liao and Alexandra La Roche",
    writer: "John Griffin, Javier Grillo-Marxuach and Vivian Lee",
    genres: ["Science fiction", "Horror"],
    seasonsWatched: 2,
    genreChars: "hsv",
    status: "On Going",
  },
  "Ginny & Georgia": {
    name: "Ginny & Georgia",
    description:
      "Teenage Ginny and her family yearn to put down roots in a picturesque New England town after years on the run.",
    year: "2021-",
    rating: "3.8",
    runningTime: "50–63 minutes",
    seasons: 2,
    episodes: 20,
    creators: "Sarah Lampert",
    director:
      "Anya Adams, Renuka Jeyapalan, Sudz Sutherland, Aleysa Young and others",
    writer:
      "Sarah Lampert, Debra J. Fisher, David Monahan, Danielle Hoover and others",
    genres: ["Comedy drama"],
    seasonsWatched: 2,
    genreChars: "cdv",
    status: "On Going",
  },
  "Gotham Knights": {
    name: "Gotham Knights",
    description:
      "Batman is dead, and a powder keg has ignited Gotham City without the Dark Knight to protect it. In the wake of Bruce Wayne's murder, his adopted son Turner Hayes is framed for his killing. With the charismatic and hard-charging District Attorney Harvey Dent and the GCPD hot on his trail, Turner must rely on allies including his best friend and formidable coder Stephanie Brown, and unlikely Batman sidekick Carrie Kelley. However, they soon learn there is a larger, more nefarious force at work within Gotham City. This team of mismatched fugitives must band together to become its next generation of saviors known as the Gotham Knights.",
    year: "2023",
    rating: "3.9",
    runningTime: "45–57 minutes",
    seasons: 1,
    episodes: 13,
    creators: "Natalie Abrams, Chad Fiveash and James Patrick Stoteraux",
    director:
      "Danny Cannon, Jeffrey Hunt, Lauren Petzke, Geoffrey Wing Shotz and others",
    writer:
      "Natalie Abrams, Chad Fiveash, James Patrick Stoteraux, David Paul Francis and others",
    genres: ["Action", "Crime drama", "Superhero"],
    seasonsWatched: 1,
    genreChars: "acd",
    status: "Cancelled",
  },
  "Grand Army": {
    name: "Grand Army",
    description:
      "Five students at the largest public high school in Brooklyn take on a chaotic world as they fight to succeed, survive, break free, and seize the future.",
    year: "2020",
    rating: "2.8",
    runningTime: "47–72 minutes",
    seasons: 1,
    episodes: 9,
    creators: "Katie Cappiello",
    director:
      "So Yong Kim, Darnell Martin, Tina Mabry, Silas Howard and others",
    writer:
      "Katie Cappiello, Hilary Bettis, Randy McKinnon, Andy Parker and others",
    genres: ["Teen drama"],
    seasonsWatched: 1,
    genreChars: "kdv",
    status: "Ended",
  },
  Halo: {
    name: "Halo",
    description:
      "Master Chief, a cybernetically enhanced super-soldier, defends humanity from the alien Covenant in the 26th century.",
    year: "2022-2024",
    rating: "3.9",
    runningTime: "40–61 minutes",
    seasons: 2,
    episodes: 17,
    creators: "Steven Kane and Kyle Killen",
    director:
      "Otto Bathurst, Roel Reiné, Jonathan Liebesman, Jessica Lowrey and others",
    writer:
      "Kyle Killen, Steven Kane, Richard E. Robbins, Silka Luisa and others",
    genres: ["Action-adventure", "Drama", "Military science fiction"],
    seasonsWatched: 2,
    genreChars: "sae",
    status: "Cancelled",
  },
  Hawkeye: {
    name: "Hawkeye",
    description:
      "Clint Barton and Kate Bishop shoot a few arrows and try to avoid becoming the target themselves.",
    year: "2021",
    rating: "4.2",
    runningTime: "40–62 minutes",
    seasons: 1,
    episodes: 6,
    creators: "Jonathan Igla",
    director: "Rhys Thomas and Bert & Bertie",
    writer:
      "Jonathan Igla, Elisa Climent, Katie Mathewson, Tanner Bean and others",
    genres: ["Action-adventure", "Buddy comedy", "Crime", "Superhero"],
    seasonsWatched: 1,
    genreChars: "cab",
    status: "On Going",
  },
  "High Potential": {
    name: "High Potential",
    description:
      "Morgan, a single mom with three kids and an exceptional mind, helps solve an unsolvable crime when she rearranges some evidence during her shift as a cleaner for the police department. When they discover she has a knack for putting things in order because of her high intellectual potential, she is brought on as a consultant to work with a by-the-book seasoned detective, Karadec. Together they form an unusual and unstoppable team.",
    year: "2024",
    rating: "",
    runningTime: "- minutes",
    seasons: 1,
    episodes: 4,
    creators: "Drew Goddard",
    director: "Alethea Jones and Marc Webb",
    writer:
      "Drew Goddard, Todd Harthan, Marc Halsey, Diane Ruggiero-Wright and others",
    genres: ["Drama", "Crime"],
    seasonsWatched: 1,
    genreChars: "bdv",
    status: "On Going",
  },
  House: {
    name: "House",
    description:
      "TDr. Gregory House, although a medical unconventional, is very skilled and experienced in leading a team of medical diagnostics. He manages to decode the many complications that arise in the hospital.",
    year: "2004-2012",
    rating: "",
    runningTime: "41–49 minutes",
    seasons: 8,
    episodes: 177,
    creators: "David Shore",
    director:
      "Deran Sarafian, Greg Yaitanes, David Straiton, Hugh Laurie and others",
    writer:
      "Lawrence Kaplow, Peter Blake, Thomas L. Moran, Doris Egan and others",
    genres: ["Medical drama", "Black comedy"],
    seasonsWatched: 3,
    genreChars: "gpv",
    status: "Ended",
  },
  "House of The Dragons": {
    name: "House of The Dragons",
    description:
      "The reign of House Targaryen begins with this prequel to popular HBO series 'Game of Thrones.' Based on George R.R. Martin's 'Fire & Blood,' 'House of the Dragon' is set nearly 200 years before the events of 'Game of Thrones,' telling the story of the Targaryen civil war with King Viserys I Targaryen's children battling for control of the Iron Throne.",
    year: "2022-",
    rating: "4.0",
    runningTime: "54–68 minutes",
    seasons: 2,
    episodes: 18,
    creators: "Ryan Condal and George R. R. Martin",
    director:
      "Miguel Sapochnik, Greg Yaitanes, Clare Kilner, Geeta Vasant Patel and others",
    writer: "George R. R. Martin, Ryan Condal, Sara Hess and Charmaine DeGraté",
    genres: ["Action", "Adventure", "Fantasy", "Serial drama"],
    seasonsWatched: 2,
    genreChars: "fda",
    status: "On Going",
  },
  "I Am Groot": {
    name: "I Am Groot",
    description:
      "I Am Groot is an American series of animated shorts created by Kirsten Lepore for the streaming service Disney+, based on the Marvel Comics featuring the character Groot.",
    year: "2022-",
    rating: "4.0",
    runningTime: "5–6 minutes",
    seasons: 1,
    episodes: 9,
    creators: "Kirsten Lepore",
    director: "Kirsten Lepore",
    writer: "Kirsten Lepore",
    genres: ["Comedy", "Family", "Science fiction", "Superhero"],
    seasonsWatched: 1,
    genreChars: "scv",
    status: "On Going",
  },
  ICarly: {
    name: "ICarly",
    description:
      "Carly and her friend Sam audition for their school's talent show while Freddy, a geek, records it and uploads it online. The recording becomes an internet rage and turns into the iCarly webcast.",
    year: "2021-2023",
    rating: "4.0",
    runningTime: "23–26 minutes",
    seasons: 3,
    episodes: 33,
    creators: "Dan Schneider",
    director:
      "Phill Lewis, Jean Sagal, Anthony Rich, Morenike Joela Evans and others",
    writers: "Ali Schouten, Jay Kogen, Steve Armogida, Jim Armogida and others",
    genres: ["Sitcom"],
    seasonsWatched: 3,
    genreChars: "ocv",
    status: "Ended",
  },
  Imposters: {
    name: "Imposters",
    description:
      "Maddie, a beautiful con artist, gets involved with men and robs them blind. When she meets Patrick, someone she is interested in, three of her previous victims are on her trail.",
    year: "2017-2018",
    rating: "3.8",
    runningTime: "40–45 minutes",
    seasons: 2,
    episodes: 20,
    creators: "Adam Brooks and Paul Adelstein",
    director: "Adam Brooks, Wayne Yip, Paul Adelstein, April Mullen and others",
    writers:
      "Adam Brooks, Paul Adelstein, Kathy Greenberg, Emily Cook and others",
    genres: ["Dark comedy"],
    seasonsWatched: 2,
    genreChars: "pvv",
    status: "Cancelled",
  },
  "Iron Fist": {
    name: "Iron Fist",
    description:
      "Danny Rand decides it is time to return to New York after 15 years. Things take a turn when he tries to claim his family's company from Harold Meachum.",
    year: "2017-2018",
    rating: "3.9",
    runningTime: "49-61 minutes",
    seasons: 2,
    episodes: 23,
    creators: "Scott Buck",
    director:
      "John Dahl, Tom Shankland, Miguel Sapochnik, Uta Briesewitz and others",
    writers:
      "Scott Buck, Quinton Peeples, Scott Reynolds, Cristine Chambers and others",
    genres: ["Action", "Drama", "Martial arts", "Superhero"],
    seasonsWatched: 2,
    genreChars: "adq",
    status: "Cancelled",
  },
  "Jessica Jones": {
    name: "Jessica Jones",
    description:
      "After Jessica meets an intelligent psychopath, he advises her to repair her relationship with Trish in order to take him down. However, a lot of heroic ideas stand against this union.",
    year: "2015-2019",
    rating: "4.3",
    runningTime: "44–56 minutes",
    seasons: 3,
    episodes: 39,
    creators: "Melissa Rosenberg",
    director:
      "S. J. Clarkson, David Petrarca, Stephen Surjik, Simon Cellan Jones and others",
    writers:
      "Melissa Rosenberg, Micah Schraft, Dana Baratta, Edward Ricourt and others",
    genres: [
      "Detective",
      "Neo-noir",
      "Psychological thriller",
      "Superhero",
      "Crime drama",
    ],
    seasonsWatched: 3,
    genreChars: "dtb",
    status: "Ended",
  },
  "John Doe": {
    name: "John Doe",
    description:
      "A mysterious man rises from the primordial waters of an isolated island, possessing knowledge of literally everything in the world except for who he is. While he searches for clues to his missing identity, he uses his unique talent to help the Seattle police department solve 'impossible' crimes. Not everyone is convinced that John Doe is a hero, however, especially Lt. Jamie Avery, who investigates him in her own way.",
    year: "2002-2003",
    rating: "4.0",
    runningTime: "44 minutes",
    seasons: 1,
    episodes: 21,
    creators: "Brandon Camp and Mike Thompson",
    director:
      "Mimi Leder, Henry Bronchtein, Bill L. Norton, Félix Enríquez Alcalá and others",
    writers:
      "Brandon Camp, Mike Thompson, Gardner Stern, Russel Friend and others",
    genres: ["Drama", "Science fiction"],
    seasonsWatched: 1,
    genreChars: "dsv",
    status: "Cancelled",
  },
  "La Casa De Papel": {
    name: "La Casa De Papel",
    description:
      "A criminal mastermind who goes by 'The Professor' has a plan to pull off the biggest heist in recorded history -- to print billions of euros in the Royal Mint of Spain. To help him carry out the ambitious plan, he recruits eight people with certain abilities and who have nothing to lose. The group of thieves take hostages to aid in their negotiations with the authorities, who strategize to come up with a way to capture The Professor. As more time elapses, the robbers prepare for a showdown with the police.",
    year: "2017-2021",
    rating: "4.3",
    runningTime: "42–76 minutes",
    seasons: 3,
    episodes: 41,
    creators: "Álex Pina",
    director: "Jesús Colmenar",
    writers: "Álex Pina",
    genres: ["Heist", "Crime drama", "Thriller"],
    seasonsWatched: 3,
    genreChars: "iab",
    status: "Ended",
  },
  "Locke & Key": {
    name: "Locke & Key",
    description:
      "Following their father's murder, three siblings move into a house filled with reality-bending keys; from the comics by Joe Hill and Gabriel Rodriguez.",
    year: "2020-2022",
    rating: "4.0",
    runningTime: "33–56 minutes",
    seasons: 3,
    episodes: 28,
    creators: "Ra'uf Glasgow and Kevin Lafferty",
    director:
      "Michael Morris, Tim Southam, Mark Tonderai-Hodges, Dawn Wilkinson and others",
    writers:
      "Joe Hill, Aron Eli Coleite, Liz Phang, Meredith Averill and others",
    genres: ["Fantasy drama", "Supernatural horror"],
    seasonsWatched: 3,
    genreChars: "hdm",
    status: "Ended",
  },
  "Lockwood & Co": {
    name: "Lockwood & Co",
    description:
      "A girl with psychic abilities joins two teen boys at the ghost-hunting agency Lockwood & Co. to fight the deadly spirits plaguing London, doing their best to save the day without any adult supervision.",
    year: "2023",
    rating: "3.7",
    runningTime: "37–49 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Joe Cornish",
    director: "William McGregor, Catherine Morshead and Joe Cornish",
    writers: "Joy Wilkinson, Kara Smith, Joe Cornish, Ed Hime and others",
    genres: ["Action-adventure", "Detective", "Drama", "Supernatural horror"],
    seasonsWatched: 1,
    genreChars: "aeh",
    status: "Cancelled",
  },
  Loki: {
    name: "Loki",
    description:
      "Loki, the God of Mischief, steps out of his brother's shadow to embark on an adventure that takes place after the events of 'Avengers: Endgame.'",
    year: "2021-",
    rating: "4.2",
    runningTime: "41–54 minutes",
    seasons: 1,
    episodes: 6,
    creators: "Michael Waldron",
    director: "Kate Herron",
    writers:
      "Michael Waldron, Elissa Karasik, Bisha K. Ali, Eric Martin and others",
    genres: [
      "Action-adventure",
      "Crime thriller",
      "Fantasy",
      "Procedural drama",
      "Science fiction",
      "Superhero",
    ],
    seasonsWatched: 2,
    genreChars: "etf",
    status: "On Going",
  },
  "Love & Death": {
    name: "Love & Death",
    description:
      "Two couples lead peaceful and happy lives in a small Texas Town. However, an extramarital affair tragically alters the course of their lives.",
    year: "2023",
    rating: "-",
    runningTime: "45-58 minutes",
    seasons: 1,
    episodes: 7,
    creators: "David E. Kelley",
    director: "Lesli Linka Glatter and Clark Johnson",
    writers: "David E. Kelley",
    genres: ["Biographical drama", "Crime"],
    seasonsWatched: 1,
    genreChars: "dbv",
    status: "Ended",
  },
  "Luke Cage": {
    name: "Luke Cage",
    description:
      "Luke Cage undergoes an experiment that accidentally gives him superpowers and makes his skin unbreakable. Things take an unexpected turn when he starts fighting corruption.",
    year: "2016-2018",
    rating: "4.1",
    runningTime: "44-69 minutes",
    seasons: 2,
    episodes: 26,
    creators: "Cheo Hodari Coker",
    director:
      "Paul McGuigan, Guillermo Navarro, Vincenzo Natali, Sam Miller and others",
    writers:
      "Cheo Hodari Coker, Matt Owens, Charles Murray, Jason Horwitch and others",
    genres: [
      "Action-adventure",
      "Crime drama",
      "Neo-blaxploitation",
      "Neo-Western",
      "Superhero",
    ],
    seasonsWatched: 2,
    genreChars: "abq",
    status: "Cancelled",
  },
  MacGyver: {
    name: "MacGyver",
    description:
      "MacGyver, a contemporary hero and role model, applies his scientific knowledge to ordinary items to create a means of escape for himself and others from impending doom.",
    year: "2016-2021",
    rating: "4.3",
    runningTime: "40–44 minutes",
    seasons: 5,
    episodes: 94,
    creators: "Peter M. Lenkov",
    director: "James Wan",
    writers: "Paul Downs Colaizzo",
    genres: ["Action-adventure"],
    seasonsWatched: 5,
    genreChars: "eav",
    status: "Ended",
  },
  "Man vs Bee": {
    name: "Man vs Bee",
    description:
      "A homeless man looking for work is mistaken by a business woman for her new house sitter. Wacky hi-jinks ensue as he tries to take care of this house while pursued by a mischievous bee.",
    year: "2022",
    rating: "4.1",
    runningTime: "10–20 minutes",
    seasons: 1,
    episodes: 9,
    creators: "Rowan Atkinson and William Davies",
    director: "David Kerr",
    writers: "William Davies",
    genres: ["Comedy", "Slapstick"],
    seasonsWatched: 1,
    genreChars: "cvv",
    status: "Ended",
  },
  Manhunt: {
    name: "Manhunt",
    description:
      "Part historical fiction, part conspiracy thriller, Edwin Stanton delves into the aftermath of the first American presidential assassination-and the fight to preserve and protect the ideals that were the foundation of Lincoln's Reconstruction plans.",
    year: "2024",
    rating: "3.8",
    runningTime: "42-55 minutes",
    seasons: 1,
    episodes: 7,
    creators: "Monica Beletsky",
    director: "Carl Franklin, John Dahl and Eva Sørhaug",
    writers:
      "Monica Beletsky, Matt Johnson, Tim Brittain, Ben H. Winters and others",
    genres: ["Conspiracy thriller", "Historical drama"],
    seasonsWatched: 1,
    genreChars: "tdv",
    status: "Ended",
  },
  "Monsters at Work": {
    name: "Monsters at Work",
    description:
      "Monsters at Work begins the day after Henry J. Waternoose III's arrest, with the Monsters, Incorporated factory making the transition to laugh power. Tylor Tuskmon, a recent Scare Major graduate from Monsters University, having previously received a letter of acceptance from Waternoose to be a scarer at the factory, is excited to work at the same company as his idol Sulley. However, Tylor is devastated to learn that the company is no longer in need of scarers, and he is reassigned to work as a mechanic on the Monsters Inc. Facilities Team (MIFT). Meanwhile, Mike and Sulley encounter the trials and tribulations of running the company.",
    year: "2021-",
    rating: "4.0",
    runningTime: "21-24 minutes",
    seasons: 2,
    episodes: 20,
    creators: "Pete Docter",
    director: "Kaitlyn Ritter, Shane Zalvin, Kay Hayes and others",
    writers:
      "Colleen Evanson, Frank Contreras, Michelle Spitz, Bobs Gannaway and others",
    genres: ["Comedy", "Fantasy"],
    seasonsWatched: 2,
    genreChars: "cfv",
    status: "On Going",
  },
  "Moon Knight": {
    name: "Moon Knight",
    description:
      "Steven Grant and mercenary Marc Spector investigate the mysteries of the Egyptian gods from inside the same body.",
    year: "2022",
    rating: "4.0",
    runningTime: "45–53 minutes",
    seasons: 1,
    episodes: 6,
    creators: "Jeremy Slater",
    director: "Mohamed Diab, Aaron Moorhead, Justin Benson",
    writers:
      "Jeremy Slater, Michael Kastelein, Beau DeMayo, Peter Cameron and others",
    genres: [
      "Action-adventure",
      "Fantasy",
      "Psychological horror",
      "Superhero",
    ],
    seasonsWatched: 1,
    genreChars: "aef",
    status: "Ended",
  },
  "Mr. Iglesias": {
    name: "Mr. Iglesias",
    description:
      "Stand-up comic Gabriel Iglesias stars in this series as a good-natured high school history teacher who tries to help gifted misfits.",
    year: "2019-2020",
    rating: "4.3",
    runningTime: "26–32 minutes",
    seasons: 3,
    episodes: 21,
    creators: "Kevin Hench",
    director:
      "Andy Ackerman, Leonard R. Garner Jr., Phill Lewis, Victor Gonzalez and others",
    writers:
      "Kevin Hench, Luisa Leschin, Isaac Gonzalez, Peter Murrieta and others",
    genres: ["Comedy", "Sitcom"],
    seasonsWatched: 3,
    genreChars: "ocv",
    status: "Ended",
  },
  "Ms. Marvel": {
    name: "Ms. Marvel",
    description:
      "Kamala is a superhero fan with an imagination, particularly when it comes to Captain Marvel; Kamala feels like she doesn't fit in at school and sometimes even at home, that is until she gets superpowers like the heroes she's looked up to.",
    year: "2022",
    rating: "3.9",
    runningTime: "38–50 minutes",
    seasons: 1,
    episodes: 6,
    creators: "Bisha K. Ali",
    director: "Adil & Bilall, Meera Menon, Sharmeen Obaid-Chinoy and others",
    writers:
      "Bisha K. Ali, Kate Gritmon, Freddy Syborn, Sabir Pirzada and others",
    genres: ["Action-adventure", "Comedy", "Coming-of-age", "Superhero"],
    seasonsWatched: 1,
    genreChars: "eca",
    status: "Ended",
  },
  "Night Has Come": {
    name: "Night Has Come",
    description:
      "After their midterm, the 10th graders of Yoo II go on a school retreat and arrive at a secluded retreat center located in the deep mountains. Then, a mysterious app is installed on the students' phones, and the deadly Mafia game begins. Not knowing what awaits them ahead, the students vote, not too seriously, for Heo Yul. However, when midnight strikes, Heo Yul kills himself, plunging everyone into a deep sleep along with the message 'Night has come' on their phones. The next day, another friend is found dead, leaving students in confusion, but soon they realize the 'Mafia Game' has become real.",
    year: "2023-",
    rating: "3.8",
    runningTime: "30 minutes",
    seasons: 1,
    episodes: 12,
    creators: "Lim Dae-wung",
    director: "Im Dae Woong",
    writers: "Kang Min Ji",
    genres: ["Thriller", "Mystery", "Horror", "Youth"],
    seasonsWatched: 1,
    genreChars: "tmh",
    status: "Ended",
  },
  "Not Dead Yet": {
    name: "Not Dead Yet",
    description:
      "Nell Serrano, a broke and newly single self-described disaster, works to restart the life and career she left behind 10 years ago; when she lands the only job she can find -- writing obituaries, she starts getting life advice from an unlikely source.",
    year: "2023-2024",
    rating: "4.0",
    runningTime: "20-22 minutes",
    seasons: 2,
    episodes: 23,
    creators: "Casey Johnson and David Windsor",
    director:
      "Dean Holland, Todd Holland, Gail Mancuso, Melanie Mayron and others",
    writers:
      "Casey Johnson, David Windsor, Marc Firek, Josh Greenberg and others",
    genres: ["Sitcom"],
    seasonsWatched: 2,
    genreChars: "ovv",
    status: "Ended",
  },
  "Orphan Black: Echoes": {
    name: "Orphan Black; Echoes",
    description:
      "Taking place in 2052, 37 years since the end of the original 'Orphan Black' series, Echoes follows the life of the now adult Kira, played by Krysten Ritter, and her wife as they try to help an amnesiac woman. The futuristic series takes a deep dive into an exploration of the scientific manipulation of human existence. A group of women weave their way into each other's lives and embark on a thrilling journey, unraveling the mystery of their identity and uncovering a heartwrenching story of love and betrayal.",
    year: "2023-",
    rating: "-",
    runningTime: "41–48 minutes",
    seasons: 1,
    episodes: 10,
    creators: "Anna Fishko",
    director: "John Fawcett, Dawn Wilkinson, Ingrid Jungermann and Samir Rehem",
    writers:
      "Anna Fishko, Sharyn Rothstein, Amy Louise Johnson and C. Quintana",
    genres: ["Science fiction", "Drama", "Thriller"],
    seasonsWatched: 1,
    genreChars: "sct",
    status: "On Going",
  },
  "Prison Break": {
    name: "Prison Break",
    description:
      "An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.",
    year: "2005-2017",
    rating: "4.4",
    runningTime: "42–44 minutes",
    seasons: 5,
    episodes: 90,
    creators: "Paul Scheuring",
    director: "Brett Ratner",
    writers: "Matt Olmstead and Nick Santora",
    genres: ["Serial drama", "Crime drama", "Action thriller"],
    seasonsWatched: 5,
    genreChars: "amt",
    status: "Ended",
  },
  "Pyramid Game": {
    name: "Pyramid Game",
    description:
      "After being voted the least popular student and becoming the target of school violence, Su-ji sets out to be at the top of the rank.",
    year: "2024",
    rating: "-",
    runningTime: "- minutes",
    seasons: 1,
    episodes: 10,
    creators: "Lee Jae-gyun",
    director: "Park So-yeon",
    writers: "Choi Soo-i",
    genres: ["Psychological thriller", "Survival", "Mystery"],
    seasonsWatched: 1,
    genreChars: "tum",
    status: "Ended",
  },
  Reacher: {
    name: "Reacher",
    description:
      "Jack Reacher, a veteran military police investigator, has recently entered civilian life when he is falsely accused of murder.",
    year: "2022-",
    rating: "4.6",
    runningTime: "42–56 minutes",
    seasons: 2,
    episodes: 16,
    creators: "Nick Santora",
    director:
      "Thomas Vincent, Sam Hill, Stephen Surjik, Christine Moore and others",
    writers:
      "Nick Santora, Scott Sullivan, Aadrita Mukerji, Cait Duffy and others",
    genres: ["Action", "Crime drama", "Detective fiction", "Thriller"],
    seasonsWatched: 2,
    genreChars: "atc",
    status: "On Going",
  },
  "Resident Evil": {
    name: "Resident Evil",
    description:
      "Fourteen years after a deadly virus caused a global apocalypse, Jade Wesker fights for survival in a world overrun by infected creatures while being haunted by her past, her father, and what happened to her sister, Billie.",
    year: "2022",
    rating: "2.9",
    runningTime: "46–63 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Andrew Dabb",
    director:
      "Bronwen Hughes, Rob Seidenglanz, Rachel Goldberg and Batan Silva",
    writers:
      "Tara Knight, Andrew Dabb, Mary Leah Sutton, Jeff Howard and others",
    genres: ["Action", "Biopunk", "Horror", "Zombie apocalypse"],
    seasonsWatched: 1,
    genreChars: "ahd",
    status: "Cancelled",
  },
  "Scream Queens": {
    name: "Scream Queens",
    description:
      "Kappa House at Wallace University is a sorority that prefers to enrol only the most elite. However, when the dean issues orders that the house should be open to all, a bloody mayhem ensues.",
    year: "2015-2016",
    rating: "3.5",
    runningTime: "42–44 minutes",
    seasons: 2,
    episodes: 23,
    creators: "Ryan Murphy, Brad Falchuk and Ian Brennan",
    director:
      "Ryan Murphy, Brad Falchuk, Ian Brennan, Bradley Buecker and others",
    writers: "Ryan Murphy, Brad Falchuk and Ian Brennan",
    genres: [
      "Comedy horror",
      "Black comedy",
      "Satire",
      "Slasher",
      "Absurdist comedy",
    ],
    seasonsWatched: 2,
    genreChars: "hcd",
    status: "Ended",
  },
  "Secret Invasion": {
    name: "Secret Invasion",
    description:
      "Nick Fury learns of a secret invasion of Earth by a faction of shapeshifting Skrulls; Fury joins his allies, and together they race against time to thwart an imminent Skrull invasion and save humanity.",
    year: "2023",
    rating: "3.8",
    runningTime: "35–55 minutes",
    seasons: 1,
    episodes: 6,
    creators: "Kyle Bradstreet",
    director: "Ali Selim",
    writers:
      "Kyle Bradstreet, Brian Tucker, Roxanne Paredes, Michael Bhim and others",
    genres: [
      "Action-adventure",
      "Spy thriller",
      "Science fiction",
      "Superhero",
    ],
    seasonsWatched: 1,
    genreChars: "aes",
    status: "Ended",
  },
  See: {
    name: "See",
    description:
      "In a society surviving without the sense of sight, a set of twins are born with the ability to see. However, Baba Voss, a warrior and the leader of a tribe, adopts them and swears to protect them.",
    year: "2019-2022",
    rating: "4.5",
    runningTime: "- minutes",
    seasons: 3,
    episodes: 24,
    creators: "Steven Knight",
    director:
      "Francis Lawrence, Anders Engström, Stephen Surjik, Frederick E.O. Toye and others",
    writers:
      "Steven Knight, Robert Levine, Hadi Nicholas Deeb, Dan Shotz and others",
    genres: ["Action-adventure", "Drama", "Science fiction", "Thriller"],
    seasonsWatched: 3,
    genreChars: "aes",
    status: "Ended",
  },
  "She-Hulk Attorney at Law": {
    name: "She-Hulk Attorney at Law",
    description:
      "Jennifer Walters has a complicated life as a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
    year: "2022",
    rating: "3.8",
    runningTime: "30–38 minutes",
    seasons: 1,
    episodes: 9,
    creators: "Jessica Gao",
    director: "Kat Coiro and Anu Valia",
    writers: "Jessica Gao, Dana Schwartz and Melissa Hunter",
    genres: [
      "Action-adventure",
      "Comedy",
      "Legal drama",
      "Science fiction",
      "Superhero",
    ],
    seasonsWatched: 1,
    genreChars: "ecd",
    status: "Ended",
  },
  Shōgun: {
    name: "Shōgun",
    description:
      "Set in Japan in the year 1600, Lord Yoshii Toranaga is fighting for his life as his enemies on the Council of Regents unite against him, when a mysterious European ship is found marooned in a nearby fishing village.",
    year: "2024",
    rating: "4.0",
    runningTime: "53-70 minutes",
    seasons: 1,
    episodes: 10,
    creators: "Rachel Kondo and Justin Marks",
    director:
      "Jonathan van Tulleken, Charlotte Brändström, Frederick E.O. Toye, Takeshi Fukunaga and others",
    writers:
      "Rachel Kondo, Justin Marks, Shannon Goss, Nigel Williams and others",
    genres: ["Historical drama", "Action"],
    seasonsWatched: 1,
    genreChars: "dav",
    status: "Ended",
  },
  "Squid Game": {
    name: "Squid Game",
    description:
      "Hundreds of cash-strapped contestants accept an invitation to compete in children's games for a tempting prize, but the stakes are deadly.",
    year: "2021",
    rating: "4.0",
    runningTime: "32–63 minutes",
    seasons: 1,
    episodes: 9,
    creators: "Hwang Dong-hyuk",
    director: "Hwang Dong-hyuk",
    writers: "Hwang Dong-hyuk",
    genres: ["Survival", "Thriller", "Horror", "Drama", "Action"],
    seasonsWatched: 1,
    genreChars: "atu",
    status: "On Going",
  },
  "Stay Close": {
    name: "Stay Close",
    description:
      "The lives of a photojournalist, a soccer mom, and a homicide detective are disturbed by a terrible event from the past.",
    year: "2021",
    rating: "3.7",
    runningTime: "39–53 minutes",
    seasons: 1,
    episodes: 9,
    creators: "Harlan Coben",
    director: "Daniel O'Hara",
    writers:
      "Danny Brocklehurst, Mick Ford, Charlotte Coben, Victoria Asare-Archer",
    genres: ["Crime drama", "Mystery-thriller"],
    seasonsWatched: 1,
    genreChars: "mbt",
    status: "Ended",
  },
  Ted: {
    name: "Ted",
    description:
      "By 1993, Ted the foul-mouthed teddy bear's moment of fame has passed. He's moved back in with his best friend, likable but awkward 16-year-old John Bennett, who lives in a working-class Boston home with his parents, Matty and Susan, and cousin Blaire. Matty's a blustering, blue-collar Bostonian who thinks he's the unequivocal boss of the house and doesn't like anyone challenging him, particularly his liberal-minded niece. Susan is kind, selfless and almost pathologically sweet when it comes to caring for her family. Blaire is a smart and politically correct college student who's not afraid to speak her mind and frequently clashes with her more traditionalist family.",
    year: "2024-",
    rating: "3.9",
    runningTime: "33-51 minutes",
    seasons: 1,
    episodes: 7,
    creators: "Seth MacFarlane",
    director: "Seth MacFarlane",
    writers:
      "Seth MacFarlane, Paul Corrigan, Brad Walsh, Dana Gould, and others",
    genres: ["Comedy"],
    seasonsWatched: 1,
    genreChars: "cvv",
    status: "On Going",
  },
  "The 8 Show": {
    name: "The 8 Show",
    description:
      "Eight individuals trapped in a mysterious eight-story building participate in a tempting but dangerous game-show where they earn money as time passes.",
    year: "2024",
    rating: "-",
    runningTime: "46-69 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Han Jae-rim",
    director: "Han Jae-rim",
    writer: "Han Jae-rim",
    genres: ["Dark comedy", "Thriller", "Satirical drama"],
    seasonsWatched: 1,
    genreChars: "ctd",
    status: "Ended",
  },
  "The Boss Baby Back in Business": {
    name: "The Boss Baby Back in Business",
    description:
      "With the support of his elder brother and partner-in-crime, Boss Baby strives to achieve a work-life balance while keeping his job at Baby Corp and simultaneously attending to his family.",
    year: "2018-2021",
    rating: "4.1",
    runningTime: "24 minutes",
    seasons: 4,
    episodes: 50,
    creators: "Ben Bromfield and Ryan Elder",
    director:
      "Matt Engstrom, Allan Jacobsen, Pete Jacobs, Christo Stamboliev, and others",
    writers:
      "Alexandra Decas, Melanie Kirschbaum, Brandon Sawyer, JD Ryznar, and others",
    genres: ["Comedy"],
    seasonsWatched: 3,
    genreChars: "cef",
    status: "Ended",
  },
  "The Defenders": {
    name: "The Defenders",
    description:
      "Four superheroes and vigilantes unite their powers in order to fight the Hand, a supervillain who threatens to destroy New York City.",
    year: "2017",
    rating: "4.1",
    runningTime: "44-55 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Douglas Petrie and Marco Ramirez",
    director:
      "S. J. Clarkson, Peter Hoar, Phil Abraham, Uta Briesewitz, and others",
    writers: "Douglas Petrie, Marco Ramirez, and Lauren Schmidt Hissrich",
    genres: ["Action", "Drama", "Superhero"],
    seasonsWatched: 1,
    genreChars: "adq",
    status: "Ended",
  },
  "The Falcon And The Winter Soldier": {
    name: "The Falcon And The Winter Soldier",
    description:
      "Falcon and the Winter Soldier are a mismatched duo who team up for a global adventure that will test their survival skills -- as well as their patience.",
    year: "2021",
    rating: "3.6",
    runningTime: "49–57 minutes",
    seasons: 1,
    episodes: 6,
    creators: "Malcolm Spellman",
    director: "Kari Skogland",
    writers:
      "Malcolm Spellman, Michael Kastelein, Derek Kolstad, Dalan Musson, and others",
    genres: [
      "Action-adventure",
      "Buddy comedy",
      "Science fiction",
      "Superhero",
    ],
    seasonsWatched: 1,
    genreChars: "cea",
    status: "Ended",
  },
  "The Flight Attendant": {
    name: "The Flight Attendant",
    description:
      "A flight attendant's life gets turned upside down after she wakes up in a hotel room with a dead man but with no memory of what happened.",
    year: "2020-2022",
    rating: "3.7",
    runningTime: "37–49 minutes",
    seasons: 2,
    episodes: 16,
    creators: "Steve Yockey",
    director:
      "Susanna Fogel, Tom Vaughan, John Strickland, Glen Winter, and others",
    writers:
      "Steve Yockey, Chris Bohjalian, Kara Lee Corthron, Ryan Jennifer Jones, and others",
    genres: ["Thriller", "Comedy drama", "Dark comedy", "Mystery"],
    seasonsWatched: 2,
    genreChars: "mct",
    status: "Ended",
  },
  "The Last Of Us": {
    name: "The Last Of Us",
    description:
      "Twenty years after a fungal outbreak ravages the planet, survivors Joel and Tess are tasked with a mission that could change everything.",
    year: "2023",
    rating: "4.4",
    runningTime: "43–81 minutes",
    seasons: 1,
    episodes: 9,
    creators: "Craig Mazin and Neil Druckmann",
    director:
      "Craig Mazin, Neil Druckmann, Jeremy Webb, Jasmila Žbanić, and others",
    writers: "Craig Mazin and Neil Druckmann",
    genres: ["Post-apocalyptic", "Drama", "Thriller"],
    seasonsWatched: 1,
    genreChars: "aew",
    status: "On Going",
  },
  "The Lazarus Project": {
    name: "The Lazarus Project",
    description:
      "An affecting exploration of modernity and the desire and ability to take charge of one's future. George finds himself living the same day repeatedly until a chance encounter reveals his ability to manipulate space-time.",
    year: "2022-",
    rating: "3.7",
    runningTime: "41–46 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Joe Barton",
    director: "Marco Kreuzpaintner, Laura Scrivano, Akaash Meeda",
    writers: "Joe Barton",
    genres: ["Science fiction", "Action", "Thriller", "Drama"],
    seasonsWatched: 1,
    genreChars: "sat",
    status: "Cancelled",
  },
  "The Night Agent": {
    name: "The Night Agent",
    description:
      "While monitoring an emergency line, an FBI agent is drawn into a deadly conspiracy involving a mole at the White House.",
    year: "2023-",
    rating: "4.0",
    runningTime: "45–56 minutes",
    seasons: 1,
    episodes: 10,
    creators: "Shawn Ryan",
    director: "Seth Gordon, Guy Ferland, Ramaa Mosley, Adam Arkin, and others",
    writers: "Shawn Ryan, Munis Rashid, Seth Fisher, Corey Deshon, and others",
    genres: ["Action", "Conspiracy thriller", "Drama"],
    seasonsWatched: 1,
    genreChars: "atd",
    status: "Ended",
  },
  "The Office": {
    name: "The Office",
    description:
      "A motley group of office workers go through hilarious misadventures at the Scranton, Pennsylvania, branch of the Dunder Mifflin Paper Company.",
    year: "2005-2013",
    rating: "4.9",
    runningTime: "22-42 minutes",
    seasons: 9,
    episodes: 201,
    creators: "Greg Daniels",
    director:
      "Steve Carell, Rainn Wilson, John Krasinski, B. J. Novak, and others",
    writers:
      "Steve Carell, Mindy Kaling, B. J. Novak, Paul Lieberstein, and others",
    genres: ["Mockumentary", "Workplace comedy", "Cringe comedy", "Sitcom"],
    seasonsWatched: 9,
    genreChars: "cov",
    status: "Ended",
  },
  "The Outsider": {
    name: "The Outsider",
    description:
      "Based on Stephen King's best-selling novel of the same name, 'The Outsider' begins by following an investigation which at first seems like it will be simple and straightforward but things change as it leads into the gruesome murder of a young boy by a seasoned cop. When an insidious supernatural force edges its way into the case, it leads the investigators to question everything they believe in. The character of Holly Gibney from 'Mr. Mercedes' is a major character in this series.",
    year: "2020",
    rating: "3.9",
    runningTime: "50-60 minutes",
    seasons: 1,
    episodes: 10,
    creators: "Richard Price",
    director:
      "Jason Bateman, Andrew Bernstein, Igor Martinović, Karyn Kusama, and others",
    writers: "Richard Price, Jessie Nickson-Lopez, Dennis Lehane",
    genres: ["Crime drama", "Mystery", "Horror"],
    seasonsWatched: 1,
    genreChars: "hbm",
    status: "Cancelled",
  },
  "The Peripheral": {
    name: "The Peripheral",
    description:
      "Set in the future when technology has subtly altered society, a woman discovers a secret connection to an alternate reality as well as a dark future of her own.",
    year: "2022-",
    rating: "4.3",
    runningTime: "55–73 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Scott B. Smith",
    director: "Vincenzo Natali, Alrick Riley",
    writers: "Scott B. Smith, Jamie Chan, Greg Plageman",
    genres: ["Science fiction", "Thriller", "Drama"],
    seasonsWatched: 1,
    genreChars: "std",
    status: "Cancelled",
  },
  "The Punisher": {
    name: "The Punisher",
    description:
      "Following the death of his family by the hands of a group of ruthless criminals, Frank Castle seeks to take revenge and punish those who are responsible for his tragedy.",
    year: "2017-2019",
    rating: "4.4",
    runningTime: "49–58 minutes",
    seasons: 2,
    episodes: 26,
    creators: "Steve Lightfoot",
    director: "Tom Shankland, Andy Goddard, Kari Skogland, Dearbhla Walsh",
    writers:
      "Steve Lightfoot, Dario Scardapane, Michael Jones-Morales, Christine Boylan",
    genres: ["Action", "Conspiracy thriller", "Crime drama", "Superhero"],
    seasonsWatched: 2,
    genreChars: "bat",
    status: "Ended",
  },
  "The Queen's Gambit": {
    name: "The Queen's Gambit",
    description:
      "Set during the Cold War era, orphaned chess prodigy Beth Harmon struggles with addiction in a quest to become the greatest chess player in the world.",
    year: "2020",
    rating: "4.0",
    runningTime: "46–67 minutes",
    seasons: 1,
    episodes: 7,
    creators: "Scott Frank and Allan Scott",
    director: "Scott Frank",
    writers: "Scott Frank",
    genres: ["Coming-of-age", "Period drama"],
    seasonsWatched: 1,
    genreChars: "dvv",
    status: "Ended",
  },
  "The Rookie": {
    name: "The Rookie",
    description:
      "Starting over isn't easy, especially for small-town guy John Nolan, who, after a life-altering incident, is pursuing his dream of becoming an LAPD officer. As the force's oldest rookie, he's met with skepticism from some higher-ups who see him as just a walking midlife crisis. If he can't keep up with the young cops and the criminals, he'll be risking lives -- including his own -- but if he can use his life experience, determination and sense of humour to give him an edge, he may just become successful in this new chapter of his life.",
    year: "2018-",
    rating: "4.6",
    runningTime: "42–45 minutes",
    seasons: 6,
    episodes: 103,
    creators: "Alexi Hawley",
    director: "Liz Friedlander",
    writers: "Alexi Hawley",
    genres: ["Police procedural", "Crime drama", "Action"],
    seasonsWatched: 6,
    genreChars: "adb",
    status: "On Going",
  },
  "The Terminal List": {
    name: "The Terminal List",
    description:
      "James Reece returns home after his entire platoon of Navy SEALs is ambushed, only to discover new dark forces working against him and endangering the ones he loves.",
    year: "2022-",
    rating: "4.1",
    runningTime: "51–65 minutes",
    seasons: 1,
    episodes: 8,
    creators: "David DiGilio",
    director:
      "Antoine Fuqua, Ellen Kuras, M. J. Bassett, Frederick E.O. Toye and others",
    writers:
      "David DiGilio, Daniel Shattuck, John Lopez, Tolu Awosika and others",
    genres: ["Action", "Conspiracy thriller", "Drama"],
    seasonsWatched: 1,
    genreChars: "adb",
    status: "Ended",
  },
  "The Wilds": {
    name: "The Wilds",
    description:
      "Teenage girls from radically different backgrounds find themselves stranded on a remote island, unaware they've just become the subjects of an elaborate social experiment.",
    year: "2020-2022",
    rating: "3.5",
    runningTime: "42–61 minutes",
    seasons: 2,
    episodes: 18,
    creators: "Sarah Streicher",
    director:
      "Susanna Fogel, John Polson, Cherie Nowlan, Haifaa Al-Mansour and others",
    writers:
      "Sarah Streicher, Daniel Paige, Tonya Kong, Shalisha Francis-Feusner and others",
    genres: ["Drama"],
    seasonsWatched: 2,
    genreChars: "dmu",
    status: "Cancelled",
  },
  "The Witcher Blood Origin": {
    name: "The Witcher Blood Origin",
    description:
      "Set more than a thousand years before the world of 'The Witcher,' seven outcasts in the elf world unite in a quest against an unstoppable power.",
    year: "2022",
    rating: "3.9",
    runningTime: "43–64 minutes",
    seasons: 1,
    episodes: 4,
    creators: "Lauren Schmidt Hissrich and Declan de Barra",
    director: "Sarah O'Gorman and Vicky Jewson",
    writers:
      "Alex Meenehan, Aaron Stewart-Ahn, Tania Lotia, Kiersten Van Horne and others",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    seasonsWatched: 1,
    genreChars: "fda",
    status: "Ended",
  },
  "The Witcher": {
    name: "The Witcher",
    description:
      "The witcher Geralt, a mutated monster hunter, struggles to find his place in a world in which people often prove more wicked than beasts.",
    year: "2019-2023",
    rating: "4.6",
    runningTime: "47–67 minutes",
    seasons: 3,
    episodes: 21,
    creators: "Lauren Schmidt Hissrich",
    director:
      "Alik Sakharov, Alex Garcia Lopez, Charlotte Brändström, Marc Jobst and others",
    writers:
      "Lauren Schmidt Hissrich, Jenny Klein, Beau DeMayo, Declan de Barra and others",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    seasonsWatched: 3,
    genreChars: "efd",
    status: "On Going",
  },
  "The Woman In The House Across The Street From The Girl In The Window": {
    name: "The Woman In The House Across The Street From The Girl In The Window",
    description:
      "A dark comedy mystery thriller where a woman becomes embroiled in a series of bizarre incidents involving her neighbors.",
    year: "2022",
    rating: "4.0",
    runningTime: "22–29 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Rachel Ramras, Hugh Davidson, Larry Dorf",
    director: "Michael Lehmann",
    writers: "Rachel Ramras, Hugh Davidson, Larry Dorf",
    genres: ["Dark comedy", "Mystery", "Thriller"],
    seasonsWatched: 1,
    genreChars: "mtc",
    status: "Ended",
  },
  "United States of Al": {
    name: "United States of Al",
    description:
      "A Marine combat veteran struggling to readjust to civilian life in Ohio finds friendship in Al, the interpreter who served with his unit in Afghanistan and has just arrived to start a new life in America.",
    year: "2021-2022",
    rating: "4.1",
    runningTime: "20 minutes",
    seasons: 2,
    episodes: 35,
    creators: "Chuck Lorre",
    director: "Mark Cendrowski and Nikki Lorre",
    writers:
      "Andy Gordon, Bobby Telatovich, Habib Zahori, Maria Ferrari and others",
    genres: ["Sitcom"],
    seasonsWatched: 2,
    genreChars: "ocv",
    status: "Cancelled",
  },
  "Wanda Vision": {
    name: "Wanda Vision",
    description:
      "Living idealized suburban lives, super-powered beings Wanda and Vision begin to suspect that everything is not as it seems.",
    year: "2021",
    rating: "4.1",
    runningTime: "30–50 minutes",
    seasons: 1,
    episodes: 9,
    creators: "Jac Schaeffer",
    director: "Matt Shakman",
    writers:
      "Jac Schaeffer, Gretchen Enders, Megan McDonnell, Bobak Esfarjani and others",
    genres: ["Drama", "Mystery", "Romance", "Sitcom", "Superhero"],
    seasonsWatched: 1,
    genreChars: "rmd",
    status: "Ended",
  },
  Wednesday: {
    name: "Wednesday",
    description:
      "While attending Nevermore Academy, Wednesday Addams attempts to master her emerging psychic ability, thwart a killing spree and solve the mystery that embroiled her parents 25 years ago.",
    year: "2022-",
    rating: "4.3",
    runningTime: "46–57 minutes",
    seasons: 1,
    episodes: 8,
    creators: "Miles Millar and Alfred Gough",
    director: "Tim Burton, Gandja Monteiro and James Marshall",
    writers:
      "Charles Addams, Miles Millar, Alfred Gough, Kayla Alpert and others",
    genres: ["Comedy horror", "Coming-of-age", "Supernatural"],
    seasonsWatched: 1,
    genreChars: "fcm",
    status: "On Going",
  },
  "What If...?": {
    name: "What If...!",
    description:
      "Reimagining noteworthy events in the Marvel Cinematic Universe and creating a multiverse of infinite possibilities.",
    year: "2021-",
    rating: "4.0",
    runningTime: "30-37 minutes",
    seasons: 2,
    episodes: 18,
    creators: "A. C. Bradley",
    director: "Bryan Andrews and Stephan Franck",
    writers: "A. C. Bradley and Matthew Chauncey",
    genres: ["Action-adventure", "Anthology", "Science fiction", "Superhero"],
    seasonsWatched: 2,
    genreChars: "aes",
    status: "On Going",
  },
  "Y The Last Man": {
    name: "Y The Last Man",
    description:
      "Based on DC Comics' acclaimed series by Brian K. Vaughan and Pia Guerra, the drama 'Y: The Last Man' traverses a post-apocalyptic world in which a cataclysmic event decimates every mammal with a Y chromosome but for one cisgender man and his pet monkey. The series follows the survivors in this new world as they struggle with their efforts to restore what was lost and build something better. 'Y: The Last Man' is a 60-issue science fiction comic book series published in 2002.",
    year: "2021",
    rating: "3.9",
    runningTime: "47–54 minutes",
    seasons: 1,
    episodes: 10,
    creators: "Eliza Clark",
    director:
      "Louise Friedberg, Daisy von Scherler Mayer, Destiny Ekaragha, Mairzee Almas and others",
    writers:
      "Pia Guerra, Brian K. Vaughan, Tian Jun Gu, Donnetta Lavinia Grays and others",
    genres: ["Action-adventure", "Drama", "Post-apocalyptic"],
    seasonsWatched: 1,
    genreChars: "dea",
    status: "Ended",
  },
  Yellowjackets: {
    name: "Yellowjackets",
    description:
      '"Yellowjackets" tells the narrative of a team of wildly talented high-school girls soccer players who survive a plane crash deep in the Ontario wilderness. The series chronicles their descent from a complicated but thriving team to warring, cannibalistic clans, while also tracking the lives they have attempted to piece back together. Sophie Nélisse, Jasmin Savoy Brown, Sophie Thatcher and Sammi Hanratty star as the teenagers, while Melanie Lynskey, Tawny Cypress, Christina Ricci and Juliette Lewis portray their adult counterparts as they reveal the truth about their survival 25 years later.',
    year: "2021-",
    rating: "-",
    runningTime: "51-61 minutes",
    seasons: 2,
    episodes: 19,
    creators: "Ashley Lyle and Bart Nickerson",
    director: "Karyn Kusama, Jamie Travis, Eva Sørhaug, Deepa Mehta and others",
    writers:
      "Jonathan Lisco, Ashley Lyle, Bart Nickerson, Sarah L. Thompson and others",
    genres: [
      "Psychological drama",
      "Horror",
      "Mystery",
      "Thriller",
      "Survival",
    ],
    seasonsWatched: 2,
    genreChars: "mtu",
    status: "On Going",
  },
  "Young Sheldon": {
    name: "Young Sheldon",
    description:
      "Sheldon Cooper, a bona fide genius, has been promoted four grades. Meanwhile, he struggles to fit in with his unintellectual family in Texas.",
    year: "2017-2024",
    rating: "4.2",
    runningTime: "18–21 minutes",
    seasons: 7,
    episodes: 141,
    creators: "Chuck Lorre and Steven Molaro",
    director:
      "Jason Alexander, Casey Childs, Timothy Marx, Craig T. Nelson and others",
    writers:
      "Chuck Lorre, Steven Molaro, Kurt Koehler, David Bickel and others",
    genres: ["Period sitcom"],
    seasonsWatched: 7,
    genreChars: "ocd",
    status: "Ended",
  },
};

const sortedSeriesData = Object.fromEntries(
  Object.entries(seriesData).sort(([a], [b]) => a.localeCompare(b))
);


const genre = {
  a: "Action",
  b: "Crime",
  c: "Comedy",
  d: "Drama",
  e: "Adventure",
  f: "Fantasy",
  g: "Medical",
  t: "Thriller",
  h: "Horror",
  m: "Mystery",
  s: "Sci-Fi",
  r: "Romance",
  w: "War",
  i: "Heist",
  o: "Sitcom",
  k: "Adolescence",
  u: "Survival",
  p: "Dark Comedy",
  q: "Superhero",
  z: "Zombie apocalypse",
  v: "",
};
